AWSTemplateFormatVersion: "2010-09-09"
Description: Monitoring of the static site

Parameters:
  Prefix:
    Description: Prefix for the general name
    Type: String
  Email:
    Description: Email address to receive notifications
    Type: String

# Create an SNS topic for sending budget alarm notifications
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${Prefix}-topic"
      TopicName: !Sub "${Prefix}-topic"

# Create subscribtion of email address to the SNS topic
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSTopic
      Endpoint: !Ref Email

# Create a budget for monitoring S3 and CloudFront costs
  Budget: 
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub "${Prefix}-budget"
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: 1
          Unit: USD
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            # The notification is configured to trigger when the estimated charges exceed 80%
            Threshold: 80
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email

# CloudWatch alarm will check the "Requests" metric of the CloudFront distribution every minute
# and will send an alarm if the sum of requests in the last five minutes is greater than 100
  CloudFrontRequestsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: !Sub "${Prefix}-cloudfront-requests"
      AlarmDescription: "Alarm for CloudFront requests"
      MetricName: "Requests"
      Namespace: "AWS/CloudFront"
      Statistic: "Sum"
      Period: 60
      EvaluationPeriods: 5
      Threshold: 100
      ComparisonOperator: "GreaterThanThreshold"
      Dimensions:
        - Name: "CloudFrontDistributionId"
          Value: !ImportValue CloudFrontDistributionId
      AlarmActions:
        - !Ref SNSTopic