AWSTemplateFormatVersion: "2010-09-09"
Description: Monitoring of the static site

Parameters:
  Prefix:
    Description: Prefix for the general name
    Type: String
  Email:
    Description: Email address to receive notifications
    Type: String

# Create an SNS topic for sending budget alarm notifications
Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Description: "Topic for sending budget alarm notifications"
    Properties:
      DisplayName: !Sub "${Prefix}-topic"
      TopicName: !Sub "${Prefix}-topic"

# Create subscribtion of email address to the SNS topic
  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSTopic
      Endpoint: !Ref Email

# Create a budget for monitoring S3 and CloudFront costs
  Budget: 
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub "${Prefix}-budget"
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: 1
          Unit: USD
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN_EQUAL_TO
            # The notification is configured to trigger when the estimated charges exceed $1
            Threshold: 1
            Subject: "AWS Cost Notification"
            Message: "The current cost has exceeded the threshold of $1"
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref Email
