region       = "eu-central-1"
aws_profile  = "default"
domain_name  = "pavlyshyn.work"
prefix       = "pavlyshyn-work"
github_owner = "Viktorpav"
github_repo  = "Viktorpav/site-of-mine"
branch_name  = "main"
