AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a static site using nested stacks

Parameters:
  DomainName:
    Type: String
  Prefix:
    Type: String
  CertificateManagerArn:
    Type: String
  HostedZoneId:
    Type: String
  TranscodeFunctionArn:
    Type: String

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://pavlyshyn-work-stack.s3.eu-central-1.amazonaws.com/services/s3_stack.yaml"
      Parameters:
        DomainName: !Ref DomainName
        TranscodeFunctionArn: !ImportValue TranscodeFunctionArn

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://pavlyshyn-work-stack.s3.eu-central-1.amazonaws.com/services/cloudfront_stack.yaml"
      Parameters:
        DomainName: !Ref DomainName
        CertificateManagerArn: !Ref CertificateManagerArn

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://pavlyshyn-work-stack.s3.eu-central-1.amazonaws.com/services/lambda_stack.yaml"
      Parameters:
        DomainName: !Ref DomainName
        Prefix: !Ref Prefix

  ACMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://pavlyshyn-work-stack.s3.eu-central-1.amazonaws.com/services/acm_stack.yaml"
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
