AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy Route53 records

Parameters:
  DomainName:
    Type: String

Resources:
  Route53Records:
    Type: AWS::Route53::RecordSetGroup
    Properties:
Route53RecordSetGroup:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    # Keep the . suffix
    HostedZoneName: !Sub "${DomainName}."
    RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt CloudFrontDistribution.DomainName
          # Set EvaluateTargetHealth to false to avoid health check issues
          EvaluateTargetHealth: false
          # Leave hardcoded, don't confuse w/ !Ref HostedZoneId
          HostedZoneId: Z2FDTNDATAQYW2
      - Name: !Sub "www.${DomainName}"
        Type: A
        AliasTarget:
          DNSName: !GetAtt CloudFrontDistribution.DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z2FDTNDATAQYW2
# No Outputs as it's not exporting any values
