name: Deploying ACM for DNS
on:
  push:
    branches:
    # Here we choose to deploy only when a push is detected on the main branch
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
  # To build the project, take a VM with latest Ubuntu OS for running the next steps
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-central-1"

    # Deploy to AWS CloudFormation
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: mystaticwebsite-acm-certificate
        template: cloudformation/acm-certificate.yaml
        parameter-overrides: "DomainName=pavlyshyn.space,HostedZoneId=Z0064882QATAQY6LFYUT"
        no-fail-on-empty-changeset: "1"